// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbcmauotgyzcnrkwioym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiY21hdW90Z3l6Y25ya3dpb3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjM3NzcsImV4cCI6MjA4ODUzOTc3N30.wYykyvuinn5hN3NX4ky1Sx1vlrhXDVw6SGlztsCWXoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});