// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxcrkbjbfphajrhwwhox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4Y3JrYmpiZnBoYWpyaHd3aG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTIwNzksImV4cCI6MjA4ODUyODA3OX0.PRGyS_923xlQEgC8QHv3zNJCfrYSzEQLJfC5otQPsac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});